CREATE GENERATOR marcasID;
CREATE GENERATOR categoriasID;
CREATE GENERATOR unidadesID;
CREATE GENERATOR listapreciosID;


SET GENERATOR marcasID TO 0;
SET GENERATOR categoriasID TO 0;
SET GENERATOR unidadesID TO 0;
SET GENERATOR listapreciosID TO 0;


