CREATE GENERATOR marcasID;
CREATE GENERATOR categoriasID;
CREATE GENERATOR unidadesID;
CREATE GENERATOR listapreciosID;
CREATE GENERATOR localidadesID;
CREATE GENERATOR ProvinciasID;
CREATE GENERATOR PaisesID;
CREATE GENERATOR TiposContactosID;
CREATE GENERATOR CondicionesFiscalesID;
CREATE GENERATOR ZonasID;

SET GENERATOR marcasID TO 0;
SET GENERATOR categoriasID TO 0;
SET GENERATOR unidadesID TO 0;
SET GENERATOR listapreciosID TO 0;
SET GENERATOR localidadesID TO 0;
SET GENERATOR ProvinciasID TO 0;
SET GENERATOR PaisesID TO 0;
SET GENERATOR TiposContactosID TO 0;
SET GENERATOR CondicionesFiscalesID TO 0;
SET GENERATOR ZonasID TO 0;


